# SELECIONA TODAS AS TABELAS
SELECT CONCAT(UCASE(SUBSTRING(TABLE_NAME, 1, 1)),LOWER(SUBSTRING(TABLE_NAME, 2))) AS 'nome' FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='admed';

# SELECIONA AS COLUNAS DE UMA TABELA
SELECT 
    ORDINAL_POSITION AS 'ordem',
    COLUMN_KEY AS 'chave',
    COLUMN_NAME AS 'nome',
    UPPER(DATA_TYPE) AS 'tipo',
    COLUMN_TYPE AS 'tipoColuna',
    CHARACTER_MAXIMUM_LENGTH AS 'tamanho',
    IS_NULLABLE AS 'nulo',
    NUMERIC_PRECISION AS 'base',
    NUMERIC_SCALE AS 'precisao',
    UPPER(EXTRA) AS 'padrao',
    COLUMN_DEFAULT AS 'valorDefault'
FROM
    INFORMATION_SCHEMA.COLUMNS 
WHERE
    TABLE_SCHEMA = 'admed'
        AND TABLE_NAME = 'curso';
        
# SELECIONA AS REFERENCIAS DE UMA TABELA
SELECT 
    CONCAT(UCASE(SUBSTRING(i.TABLE_NAME, 1, 1)),LOWER(SUBSTRING(i.TABLE_NAME, 2))) AS 'tabela',
    CONCAT(UCASE(SUBSTRING(k.REFERENCED_TABLE_NAME, 1, 1)),LOWER(SUBSTRING(k.REFERENCED_TABLE_NAME, 2))) AS 'tabelaReferencia',
    k.COLUMN_NAME AS 'idReferencia'
FROM
    information_schema.TABLE_CONSTRAINTS i
        LEFT JOIN
    information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE
    i.CONSTRAINT_TYPE = 'FOREIGN KEY'
        AND i.TABLE_SCHEMA = 'admed'
        AND i.TABLE_NAME = 'curso';
        
# SELECIONA AS REFERÊNCIAS EXTERNAS DE UMA TABELA
SELECT
	CONCAT(UCASE(SUBSTRING(REFERENCED_TABLE_NAME, 1, 1)),LOWER(SUBSTRING(REFERENCED_TABLE_NAME, 2))) AS 'tabela',
	CONCAT(UCASE(SUBSTRING(TABLE_NAME, 1, 1)),LOWER(SUBSTRING(TABLE_NAME, 2))) AS 'tabelaExterna',
  	COLUMN_NAME AS 'colunaReferencia',
  	REFERENCED_COLUMN_NAME AS 'colunaReferenciada'
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    TABLE_SCHEMA = 'admed'
			AND REFERENCED_TABLE_NAME = 'conversa';